### PR TITLE
drforbin added (deluge, fail2ban, but, smartd)

### PR DESCRIPTION
**Pull request by drforbin**
Here are the changes I made. 
Let me know if I can help.

Drforbin.

### CODE REVIEW

**Comment by cromerc** [comment]
Just a couple of small issues before I merge this.

The shebang line is incorrect in some of the init sripts. They should be:
`#!/usr/bin/openrc-run`
Arch Linux does not use sbin, everything is in "/usr/bin". Your scripts don't work correctly because of this, OpenRC cannot keep track if a service is running or stopped if the shebang line is incorrect.

It's okay to have your name and email in the maintainer line, but you should remove your email from the pkgdesc variable in the PKGBUILD files.

The only other issue is purely cosmetic, the scripts are called "OpenRC" but you have "Open rc" in your package descriptions.

Once these issues are changed I will merge your commits into the repo.

**Comment by drforbin** [comment]
Okay. Will get on it. Strange related to sbin issue I tested all the scripts and they work.
Will get back with you.

**Comment by cromerc** [comment]
The scripts do work, however openrc can lose track of their status. Run the command rc-status, there is a high probability that those that do not have "/usr/bin/openrc-run" in them will be missing from that list of services. This happens when the shebang line is incorrect.

**Comment by drforbin** [comment]
Please review changes made as per your request.

**Pull request merged**
